title: Nick Pfister
description: Software engineer with a passion for creating apps, games, graphics, and everything useful.

collections:
  home:

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"